name: Release

on:
  release:
    types: [published]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Run build
        run: npm run build:prod
      - name: Upload dist bundle
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  deploy-to-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: dist
      - run: cd distribution && npx chrome-webstore-upload-cli upload --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  deploy-to-firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: dist
      - run: cd distribution && npx web-ext-submit
        env:
          WEB_EXT_ID: ${{ secrets.WEB_EXT_ID }}
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
